# SEED V

In [ ]:
def split_train_test(path):
  train_flag = 0
  test_flag = 0
  label = pd.read_csv('./SEED5/label.txt', header = None).to_numpy()
  person = os.listdir(path)
  for name in person:
    for times in range(3):
      for train in range(0,10):
        cur_label = label[times][train]
        if train_flag == 0:
          train_flag = 1
          train_set = np.load(path+name+'/'+str(times)+'/DE_'+str(train)+'.npy')
          train_set = train_set.reshape((310, train_set.shape[2])).T
          cur_label_set = np.full(((train_set.shape[0])), cur_label)
          train_set = np.insert(train_set, 0, cur_label_set, axis=1)
        else:
          train_cur = np.load(path+name+'/'+str(times)+'/DE_'+str(train)+'.npy')
          train_cur = train_cur.reshape((310, train_cur.shape[2])).T
          cur_label_set = np.full(((train_cur.shape[0])), cur_label)
          train_cur = np.insert(train_cur, 0, cur_label_set, axis=1)
          train_set = np.concatenate((train_set, train_cur), axis=0)
      for test in range(10,15):
        cur_label = label[times][test]
        if test_flag == 0:
          test_flag = 1
          test_set = np.load(path+name+'/'+str(times)+'/DE_'+str(test)+'.npy')
          test_set = test_set.reshape((310, test_set.shape[2])).T
          cur_label_set = np.full(((test_set.shape[0])), cur_label)
          test_set = np.insert(test_set, 0, cur_label_set, axis=1)
        else:
          test_cur = np.load(path+name+'/'+str(times)+'/DE_'+str(test)+'.npy')
          test_cur = test_cur.reshape((310, test_cur.shape[2])).T
          cur_label_set = np.full(((test_cur.shape[0])), cur_label)
          test_cur = np.insert(test_cur, 0, cur_label_set, axis=1)
          test_set = np.concatenate((test_set, test_cur), axis=0)
  trainx = train_set[:,1:]
  trainy = train_set[:,0]
  testx = test_set[:,1:]
  testy = test_set[:,0]
  return trainx, trainy, testx, testy
def read_all(path):
  flag = 0
  person = os.listdir(path)
  for name in person:
    for times in range(3):
      for data in range(0,15):
        cur_label = label[times][data]
        if flag == 0:
          flag = 1
          data_set = np.load(path+name+'/'+str(times)+'/DE_'+str(data)+'.npy')
          data_set = data_set.reshape((310, data_set.shape[2])).T
          cur_label_set = np.full(((data_set.shape[0])), cur_label)
          data_set = np.insert(data_set, 0, cur_label_set, axis=1)
        else:
          data_cur = np.load(path+name+'/'+str(times)+'/DE_'+str(data)+'.npy')
          data_cur = data_cur.reshape((310, data_cur.shape[2])).T
          cur_label_set = np.full(((data_cur.shape[0])), cur_label)
          data_cur = np.insert(data_cur, 0, cur_label_set, axis=1)
          data_set = np.concatenate((data_set, data_cur), axis=0)

  X = data_set[:,1:]
  y = data_set[:,0]
  return X, y

def split_fold(path):
  fold1_flag = 0
  fold2_flag = 0
  fold3_flag = 0
  person = os.listdir(path)
  label = pd.read_csv('./SEED5/label.txt', header = None).to_numpy()
  for name in person:
    for times in range(3):
      for first in range(0,5):
        cur_label = label[times][first]
        if fold1_flag == 0:
          fold1_flag = 1
          set_1 = np.load(path+name+'/'+str(times)+'/DE_'+str(first)+'.npy')
          set_1 = set_1.reshape((310, set_1.shape[2])).T
          cur_label_set = np.full(((set_1.shape[0])), cur_label)
          set_1 = np.insert(set_1, 0, cur_label_set, axis=1)
        else:
          data_cur = np.load(path+name+'/'+str(times)+'/DE_'+str(first)+'.npy')
          data_cur = data_cur.reshape((310, data_cur.shape[2])).T
          cur_label_set = np.full(((data_cur.shape[0])), cur_label)
          data_cur = np.insert(data_cur, 0, cur_label_set, axis=1)
          set_1 = np.concatenate((set_1, data_cur), axis=0)
      for second in range(5,10):
        cur_label = label[times][second]
        if fold2_flag == 0:
          fold2_flag = 1
          set_2 = np.load(path+name+'/'+str(times)+'/DE_'+str(second)+'.npy')
          set_2 = set_2.reshape((310, set_2.shape[2])).T
          cur_label_set = np.full(((set_2.shape[0])), cur_label)
          set_2 = np.insert(set_2, 0, cur_label_set, axis=1)
        else:
          data_cur = np.load(path+name+'/'+str(times)+'/DE_'+str(second)+'.npy')
          data_cur = data_cur.reshape((310, data_cur.shape[2])).T
          cur_label_set = np.full(((data_cur.shape[0])), cur_label)
          data_cur = np.insert(data_cur, 0, cur_label_set, axis=1)
          set_2 = np.concatenate((set_2, data_cur), axis=0)
      for third in range(10,15):
        cur_label = label[times][third]
        if fold3_flag == 0:
          fold3_flag = 1
          set_3 = np.load(path+name+'/'+str(times)+'/DE_'+str(third)+'.npy')
          set_3 = set_3.reshape((310, set_3.shape[2])).T
          cur_label_set = np.full(((set_3.shape[0])), cur_label)
          set_3 = np.insert(set_3, 0, cur_label_set, axis=1)
        else:
          data_cur = np.load(path+name+'/'+str(times)+'/DE_'+str(third)+'.npy')
          data_cur = data_cur.reshape((310, data_cur.shape[2])).T
          cur_label_set = np.full(((data_cur.shape[0])), cur_label)
          data_cur = np.insert(data_cur, 0, cur_label_set, axis=1)
          set_3 = np.concatenate((set_3, data_cur), axis=0)
  firstx = set_1[:,1:]
  firsty = set_1[:,0]
  secondx = set_2[:,1:]
  secondy = set_2[:,0]
  thirdx = set_3[:,1:]
  thirdy = set_3[:,0]

  return firstx, firsty, secondx, secondy, thirdx, thirdy


def testset_movie(path):
  fold1_flag = 0
  fold2_flag = 0
  fold3_flag = 0
  person = os.listdir(path)
  label = pd.read_csv('./SEED5/label.txt', header = None).to_numpy()
  set_1 = []
  set_2 = []
  set_3 = []
  test_1_y = []
  test_2_y = []
  test_3_y = []
  for name in person:
    for times in range(3):
      for first in range(0,5):
        cur_label = label[times][first]

        data_cur = np.load(path+name+'/'+str(times)+'/DE_'+str(first)+'.npy')
        data_cur = data_cur.reshape((310, data_cur.shape[2])).T
        cur_label_set = np.full(((data_cur.shape[0])), cur_label)
        test_1_y.append(cur_label_set)
        #data_cur = np.insert(data_cur, 0, cur_label_set, axis=1)
        set_1.append(data_cur)
      for second in range(5,10):
        cur_label = label[times][second]

        data_cur = np.load(path+name+'/'+str(times)+'/DE_'+str(second)+'.npy')
        data_cur = data_cur.reshape((310, data_cur.shape[2])).T
        cur_label_set = np.full(((data_cur.shape[0])), cur_label)
        test_2_y.append(cur_label_set)
        #data_cur = np.insert(data_cur, 0, cur_label_set, axis=1)
        set_2.append(data_cur)
      for third in range(10,15):
        cur_label = label[times][third]

        data_cur = np.load(path+name+'/'+str(times)+'/DE_'+str(third)+'.npy')
        data_cur = data_cur.reshape((310, data_cur.shape[2])).T
        cur_label_set = np.full(((data_cur.shape[0])), cur_label)
        test_3_y.append(cur_label_set)
        #data_cur = np.insert(data_cur, 0, cur_label_set, axis=1)
        set_3.append(data_cur)

  return set_1, set_2, set_3, test_1_y, test_2_y, test_3_y

import numpy as np
import pandas as pd
import os

seed5path = './data/SEED5/EEG'
X1, y1, X2, y2, X3, y3 = split_fold(seed5path)

#test_m1, test_m2, test_m3, ty1, ty2, ty3= testset_movie(seed5path)
X1.shape, y1, X2.shape, y2, X3.shape, y3

((8512, 310),
 array([4., 4., 4., ..., 4., 4., 4.]),
 (10672, 310),
 array([4., 4., 4., ..., 1., 1., 1.]),
 (9984, 310),
 array([4., 4., 4., ..., 0., 0., 0.]))

In [ ]:
# preprocess
import numpy as np
import pandas as pd
from sklearn import preprocessing
import pandas as pd

#EEG data
X_fold1 = np.concatenate((X1, X2), axis=0)
X_fold2 = np.concatenate((X1, X3), axis=0)
X_fold3 = np.concatenate((X2, X3), axis=0)
y_fold1 = np.concatenate((y1, y2), axis=0)
y_fold2 = np.concatenate((y1, y3), axis=0)
y_fold3 = np.concatenate((y2, y3), axis=0)

std_fold1 = preprocessing.StandardScaler()
std_fold2 = preprocessing.StandardScaler()
std_fold3 = preprocessing.StandardScaler()
# preprocess by standard scaler for every group of data (EEG)
X_fold1 = std_fold1.fit_transform(X_fold1)
X_fold2 = std_fold2.fit_transform(X_fold2)
X_fold3 = std_fold3.fit_transform(X_fold3)
x_test1 = std_fold1.transform(X3)
x_test2 = std_fold2.transform(X2)
x_test3 = std_fold3.transform(X1)

# convert to 4D
X1_CNN = X_fold1.reshape((X_fold1.shape[0], 1,1, X_fold1.shape[1]))
X2_CNN = X_fold2.reshape((X_fold2.shape[0], 1,1, X_fold2.shape[1]))
X3_CNN = X_fold3.reshape((X_fold3.shape[0], 1,1, X_fold3.shape[1]))
Xtest1_CNN = x_test1.reshape((x_test1.shape[0], 1,1, x_test1.shape[1]))
Xtest2_CNN = x_test2.reshape((x_test2.shape[0], 1,1, x_test2.shape[1]))
Xtest3_CNN = x_test3.reshape((x_test3.shape[0], 1,1, x_test3.shape[1]))

from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse=False)
order = np.array([0,1,2,3,4])
order = order.reshape(len(order), 1)
onehot_encoder.fit(order)

y_fold1 = y_fold1.reshape(len(y_fold1), 1)
y_fold2 = y_fold2.reshape(len(y_fold2), 1)
y_fold3 = y_fold3.reshape(len(y_fold3), 1)
y1_test = y3.reshape(len(y3), 1)
y2_test = y2.reshape(len(y2), 1)
y3_test = y1.reshape(len(y1), 1)

Y1_cat = onehot_encoder.transform(y_fold1)
Y2_cat = onehot_encoder.transform(y_fold2)
Y3_cat = onehot_encoder.transform(y_fold3)
Y1_test_cat = onehot_encoder.transform(y1_test)
Y2_test_cat = onehot_encoder.transform(y2_test)
Y3_test_cat = onehot_encoder.transform(y3_test)

Y1_CNN = Y1_cat.reshape((Y1_cat.shape[0], 1,1, Y1_cat.shape[1]))
Y2_CNN = Y2_cat.reshape((Y2_cat.shape[0], 1,1, Y2_cat.shape[1]))
Y3_CNN = Y3_cat.reshape((Y3_cat.shape[0], 1,1, Y3_cat.shape[1]))
Y1_test_CNN = Y1_test_cat.reshape((Y1_test_cat.shape[0], 1,1, Y1_test_cat.shape[1]))
Y2_test_CNN = Y2_test_cat.reshape((Y2_test_cat.shape[0], 1,1, Y2_test_cat.shape[1]))
Y3_test_CNN = Y3_test_cat.reshape((Y3_test_cat.shape[0], 1,1, Y3_test_cat.shape[1]))
